name: dailyboost
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:  
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.5
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.8.0+1
  share_plus: ^11.0.0
  provider: ^6.1.4
  path_provider: ^2.1.4  
  permission_handler: ^12.0.0+1
  google_sign_in: ^6.3.0
  device_info_plus: ^11.4.0  
  geolocator: ^14.0.0
  uuid: ^4.5.1  
  shimmer: ^3.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_analytics: ^11.0.0
  supabase_flutter: ^2.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  
  assets:
    - assets/icons/